import { NextRequest } from "next/server";
import {
  handleImagesUpload,
  handleImagesUploaded,
} from "../ppt/handlers/images";

/**
 * Runtime configuration for this API route.
 * - nodejs: Runs on Node.js runtime (required for file system access)
 * - maxDuration: Maximum execution time of 300 seconds (5 minutes)
 * - force-dynamic: Always generates dynamic responses (no caching)
 */
export const runtime = "nodejs";
export const maxDuration = 300;
export const dynamic = "force-dynamic";

/**
 * Handles GET requests to retrieve all user-uploaded images.
 *
 * Returns a list of images that were uploaded by users (not generated by AI).
 * This endpoint is useful for displaying a gallery of uploaded images or
 * allowing users to manage their image library.
 *
 * @param request - The HTTP request object (unused, but required by Next.js).
 * @returns A JSON response containing an array of image objects with metadata
 *   and URL-accessible paths.
 *
 * @example
 * ```typescript
 * // Request: GET /api/v1/images
 * // Response: [{ id: "abc-123", path: "/app_data/images/...", ... }]
 * ```
 */
export async function GET(request: NextRequest) {
  // GET returns list of uploaded images
  return handleImagesUploaded();
}

/**
 * Handles POST requests to upload an image file.
 *
 * Accepts a multipart/form-data request with an image file, validates its size,
 * saves it to storage, and creates a database record. The uploaded image can
 * then be used in presentation slides.
 *
 * Request body (multipart/form-data):
 * - `file` (required): Image file to upload (JPEG, PNG, GIF, etc.)
 *
 * @param request - The HTTP request object containing the image file in form data.
 * @returns A JSON response with image metadata including ID and URL path.
 *
 * @example
 * ```typescript
 * // Request: POST /api/v1/images
 * // Body: multipart/form-data with file field
 * // Response: { id: "abc-123", path: "/app_data/images/...", message: "..." }
 * ```
 */
export async function POST(request: NextRequest) {
  return handleImagesUpload(request);
}
