import { NextRequest } from "next/server";

/**
 * Runtime configuration for this API route.
 * - nodejs: Runs on Node.js runtime (required for streaming and LLM access)
 * - maxDuration: Maximum execution time of 300 seconds (5 minutes)
 * - force-dynamic: Always generates dynamic responses (no caching)
 */
export const runtime = "nodejs";
export const maxDuration = 300;
export const dynamic = "force-dynamic";

/**
 * Handles GET requests to stream slide content generation in real-time.
 *
 * Creates a Server-Sent Events (SSE) stream that sends slide content to the
 * client as it is generated by the LLM. This provides a responsive user
 * experience where slides appear progressively rather than all at once.
 *
 * Route parameter:
 * - `id`: The unique identifier of the presentation to generate slides for
 *
 * The stream sends various event types:
 * - `heartbeat`: Keep-alive messages
 * - `meta`: Presentation metadata
 * - `slides_init`: Initial placeholder slides
 * - `slide_delta`: Incremental content updates
 * - `slide`: Complete slide objects
 * - `progress`: Progress updates
 * - `complete`: Final completion event
 *
 * @param _request - The HTTP request object (unused, but required by Next.js).
 * @param context - Next.js route context containing dynamic route parameters.
 * @returns An HTTP Response with SSE stream (Content-Type: text/event-stream).
 *
 * @example
 * ```typescript
 * // Client connects to: GET /api/v1/presentations/stream/abc-123
 * // Receives SSE stream with slide updates in real-time
 * ```
 */
export async function GET(
  _request: NextRequest,
  context: { params: Promise<{ id: string }> },
) {
  const params = await context.params;
  const presentationId = params.id;

  // Dynamic import to avoid loading handler unless needed
  const { handlePresentationStream } = await import(
    "../../../ppt/handlers/presentation",
  );
  return handlePresentationStream(presentationId);
}
