/**
 * Type definitions for streaming-related functionality.
 *
 * These types are used throughout the presentation generation and streaming
 * system to ensure type safety and provide clear contracts for data structures
 * used in Server-Sent Events (SSE) streaming, delta parsing, and content generation.
 */

/**
 * Represents a single slide outline (high-level description).
 *
 * Outlines define what content each slide should contain before actual
 * content generation begins. They are generated by LLM and follow VC
 * pitch deck standards.
 */
export type Outline = {
  /** Text description of the slide content (e.g., "INTRO: Company tagline"). */
  content: string;
};

/**
 * Represents a single layout slide definition within a template.
 *
 * Layout slides define the structure and schema for slide content.
 * Multiple layout slides can be combined to create a complete template.
 */
export type LayoutSlide = {
  /** Unique identifier for this layout slide (e.g., "layout-1"). */
  id?: string;
  /**
   * JSON schema defining the structure of slide content.
   * This schema is used to generate placeholder content and validate
   * LLM-generated content.
   */
  json_schema?: Record<string, unknown>;
};

/**
 * Represents a complete layout template configuration.
 *
 * A layout template contains multiple slide layouts and configuration
 * for how they should be applied (sequentially or cyclically).
 */
export type LayoutPayload = {
  /** Human-readable name of the layout template (e.g., "Modern Pitch Deck"). */
  name?: string;
  /**
   * Whether layouts should be applied sequentially (true) or cyclically (false).
   * - Sequential: slide 0 → layout 0, slide 1 → layout 1, slide 2 → layout 2, etc.
   * - Cyclic: slide 0 → layout 0, slide 1 → layout 1, slide 2 → layout 0, etc.
   */
  ordered?: boolean;
  /** Array of layout slide definitions that make up this template. */
  slides?: LayoutSlide[];
};

/**
 * Represents a complete slide with all its content and metadata.
 *
 * This type is used when returning slides to clients and storing them
 * in the database. It includes both the structured content and metadata
 * like layout assignment and speaker notes.
 */
export type SlideResponse = {
  /** Unique identifier for the slide (UUID). */
  id: string;
  /** Unique identifier of the parent presentation. */
  presentation: string;
  /** Name of the layout group this slide belongs to (from template). */
  layout_group: string | null;
  /** Unique identifier of the specific layout template used for this slide. */
  layout: string | null;
  /** Zero-based index of this slide within the presentation. */
  index: number;
  /** Speaker notes text for this slide (presenter's private notes). */
  speaker_note: string;
  /**
   * Structured content object matching the layout's JSON schema.
   * Contains all text, images, charts, and other content for the slide.
   */
  content: Record<string, unknown>;
};

/**
 * Payload structure for updating a slide.
 *
 * All fields are optional to support partial updates. Used when
 * editing slides or updating slide content.
 */
export type SlideUpdatePayload = {
  /** Unique identifier of the slide to update. */
  id?: string;
  /** Layout group name (from template). */
  layout_group?: string | null;
  /** Layout template identifier. */
  layout?: string | null;
  /** Zero-based index within the presentation. */
  index?: number;
  /** Speaker notes text. */
  speaker_note?: string | null;
  /** Structured content object matching the layout schema. */
  content?: Record<string, unknown>;
  /** HTML representation of the slide (for preview/export). */
  html_content?: string | null;
};

/**
 * Callback function type for outline delta updates.
 *
 * Called when outline content is detected or updated during streaming.
 * Used by the outline delta parser to send incremental updates to clients.
 *
 * @param index - Zero-based index of the outline being updated.
 * @param content - Current content string for the outline.
 */
export type OutlineDeltaHandler = (index: number, content: string) => void;

/**
 * Configuration options for outline delta parser.
 *
 * Used when creating a parser to extract outline content from streaming JSON.
 */
export type OutlineDeltaParserOptions = {
  /**
   * Minimum milliseconds between delta updates for the same outline.
   * Throttles updates to prevent overwhelming the client with rapid changes.
   */
  minIntervalMs?: number;
  /** Callback function called when outline content is detected or updated. */
  onDelta: OutlineDeltaHandler;
};

/**
 * Callback function type for slide content delta updates.
 *
 * Called when a field value is detected or updated during slide content streaming.
 * Used by the slide delta parser to send incremental field updates to clients.
 *
 * @param payload - Delta update payload containing:
 *   - index: Zero-based index of the slide
 *   - path: Field path in dot notation (e.g., "title", "items[0].value")
 *   - value: Current field value as a string
 */
export type SlideDeltaHandler = (payload: {
  index: number;
  path: string;
  value: string;
}) => void;

/**
 * Configuration options for slide content delta parser.
 *
 * Used when creating a parser to extract field values from streaming JSON
 * during slide content generation.
 */
export type SlideDeltaParserOptions = {
  /** Zero-based index of the slide being parsed (included in delta updates). */
  slideIndex: number;
  /**
   * Minimum milliseconds between delta updates for the same field path.
   * Throttles updates to prevent overwhelming the client with rapid changes.
   */
  minIntervalMs?: number;
  /** Callback function called when a field value is detected or updated. */
  onDelta: SlideDeltaHandler;
};

/**
 * Represents a segment in a path through nested slide content.
 *
 * Used to build dot-notation paths like "title" or "items[0].value".
 * Paths are used to identify specific fields in slide content for delta updates.
 */
export type SlidePathSegment =
  | { type: "key"; key: string } // Object key (e.g., "title")
  | { type: "index"; index: number }; // Array index (e.g., [0])

/**
 * JSON schema type for slide content structure.
 *
 * This is a simplified JSON schema that defines the structure of slide content.
 * Used to generate placeholder content and validate LLM-generated content.
 * Supports nested objects, arrays, enums, and basic types.
 */
export type SlideSchema = {
  /** JSON schema type (e.g., "string", "number", "object", "array"). */
  type?: string;
  /**
   * Properties for object types. Maps property names to their schemas.
   * Used for nested object structures.
   */
  properties?: Record<string, SlideSchema>;
  /**
   * Schema for array item types. Used when type is "array".
   * All items in the array follow this schema.
   */
  items?: SlideSchema;
  /**
   * Enum values for this field. If provided, the field value must be
   * one of these values.
   */
  enum?: unknown[];
  /** Minimum number of items for array types. */
  minItems?: number;
  /** Maximum number of items for array types. */
  maxItems?: number;
};

/**
 * Represents an image field in slide content.
 *
 * Image fields have a special structure with two properties:
 * - __image_prompt__: Text description used to generate the image
 * - __image_url__: URL to the generated or uploaded image
 *
 * These fields are processed separately from regular content fields
 * to handle image generation and replacement.
 */
export type ImageField = {
  /** URL path to the image file (generated or uploaded). */
  __image_url__: string;
  /** Text prompt describing the image to generate (used by AI image generation). */
  __image_prompt__: string;
};
