import { NextRequest } from "next/server";
import { handleImagesUploaded } from "../../ppt/handlers/images";

/**
 * Runtime configuration for this API route.
 * - nodejs: Runs on Node.js runtime (required for database access)
 * - maxDuration: Maximum execution time of 300 seconds (5 minutes)
 * - force-dynamic: Always generates dynamic responses (no caching)
 */
export const runtime = "nodejs";
export const maxDuration = 300;
export const dynamic = "force-dynamic";

/**
 * Handles GET requests to retrieve all user-uploaded images.
 *
 * Returns a list of images that were uploaded by users (not generated by AI).
 * This endpoint is useful for displaying a gallery of uploaded images.
 *
 * @param _request - The HTTP request object (unused, but required by Next.js).
 * @returns A JSON response containing an array of uploaded image objects.
 *
 * @example
 * ```typescript
 * // Request: GET /api/v1/images/uploaded
 * // Response: [{ id: "abc-123", path: "/app_data/images/...", ... }]
 * ```
 */
export async function GET(_request: NextRequest) {
  return handleImagesUploaded();
}
