import { promises as fs } from "node:fs";
import { v4 as uuidv4 } from "uuid";

import {
  createImageAsset,
  deleteImageById,
  getImageById,
  listImages,
} from "@/server/db/images";
import { generateImageFromPrompt, saveUploadedImage } from "@/server/images";

import { MAX_IMAGE_UPLOAD_BYTES } from "../utils/constants";
import { errorResponse, jsonResponse } from "../utils/responses";
import { toAppDataUrl } from "../utils/storage";

/**
 * Handles GET requests to generate an image from a text prompt using AI.
 *
 * Uses an image generation service (typically an AI model) to create an image
 * based on a text description. The generated image is saved to storage and
 * a database record is created to track it. The image can then be used in
 * presentation slides.
 *
 * Query parameters:
 * - `prompt` (required): Text description of the image to generate
 *
 * The generated image is stored in the app's image directory and marked as
 * not uploaded (is_uploaded: false) to distinguish it from user-uploaded images.
 *
 * @param url - URL object containing the query parameter with the image prompt.
 * @returns A JSON response containing the URL path to the generated image,
 *   formatted as an app data URL (e.g., "/app_data/images/...")
 *
 * @throws Returns error responses for:
 *   - 400: Missing required `prompt` parameter
 *   - 500: Image generation failed (API error, storage error, etc.)
 *
 * @example
 * ```typescript
 * // Request: GET /api/v1/images/generate?prompt=a%20sunset%20over%20mountains
 * const url = new URL(request.url);
 * const response = await handleImagesGenerate(url);
 * // Response: "/app_data/images/abc-123.png"
 * ```
 */
export const handleImagesGenerate = async (url: URL) => {
  const prompt = url.searchParams.get("prompt") || "";
  if (!prompt) {
    return errorResponse("prompt is required");
  }
  try {
    // Generate image using AI image generation service
    const imagePath = await generateImageFromPrompt(prompt);
    
    // Create database record to track the generated image
    const record = await createImageAsset({
      id: uuidv4(),
      path: imagePath,
      is_uploaded: false, // Mark as AI-generated, not user-uploaded
    });
    
    // Return URL-accessible path to the image
    return jsonResponse(toAppDataUrl(record.path));
  } catch (error) {
    console.error("Image generation failed:", error);
    return errorResponse("Failed to generate image", 500);
  }
};

/**
 * Handles GET requests to retrieve all AI-generated images.
 *
 * Returns a list of all images that were generated by AI (not uploaded by users).
 * This is useful for displaying a gallery of generated images or allowing users
 * to reuse previously generated images.
 *
 * @returns A JSON response containing an array of image objects, each with:
 *   - `id`: Unique identifier
 *   - `path`: URL-accessible path to the image file
 *   - `is_uploaded`: Boolean (always false for generated images)
 *   - `created_at`: Timestamp when the image was generated
 *
 * @example
 * ```typescript
 * // Request: GET /api/v1/images/generated
 * const response = await handleImagesGenerated();
 * // Response: [{ id: "abc-123", path: "/app_data/images/...", ... }, ...]
 * ```
 */
export const handleImagesGenerated = async () => {
  // List all images marked as not uploaded (i.e., AI-generated)
  const imagesList = await listImages(false);
  
  // Convert file paths to URL-accessible paths
  const images = imagesList.map((image) => ({
    ...image,
    path: toAppDataUrl(image.path),
  }));
  return jsonResponse(images);
};

/**
 * Handles POST requests to upload an image file.
 *
 * Accepts a multipart/form-data request with an image file, validates its size,
 * saves it to storage, and creates a database record. The uploaded image can
 * then be used in presentation slides.
 *
 * Request body (multipart/form-data):
 * - `file` (required): Image file to upload (JPEG, PNG, GIF, etc.)
 *
 * Validation:
 * - File must be a valid File object
 * - File size must not exceed MAX_IMAGE_UPLOAD_BYTES (5MB default)
 *
 * @param request - The HTTP request object containing the image file in form data.
 * @returns A JSON response containing:
 *   - `id`: Unique identifier for the uploaded image
 *   - `path`: URL-accessible path to the saved image file
 *   - `message`: Success message
 *
 * @throws Returns error responses for:
 *   - 400: Missing file or file exceeds maximum size
 *   - 500: File save operation failed
 *
 * @example
 * ```typescript
 * // Request: POST /api/v1/images
 * // Body: multipart/form-data with file field
 * const response = await handleImagesUpload(request);
 * // Response: {
 * //   id: "abc-123",
 * //   path: "/app_data/images/uploaded-abc-123.png",
 * //   message: "Image uploaded successfully"
 * // }
 * ```
 */
export const handleImagesUpload = async (request: Request) => {
  const formData = await request.formData();
  const file = formData.get("file");
  
  // Validate that a file was provided
  if (!(file instanceof File)) {
    return errorResponse("file is required");
  }
  
  // Validate file size against maximum allowed
  if (file.size > MAX_IMAGE_UPLOAD_BYTES) {
    return errorResponse("Image exceeded max upload size");
  }
  
  // Save the uploaded file to storage
  const imagePath = await saveUploadedImage(file);
  
  // Create database record to track the uploaded image
  const record = await createImageAsset({
    id: uuidv4(),
    path: imagePath,
    is_uploaded: true, // Mark as user-uploaded (not AI-generated)
  });
  
  return jsonResponse({
    id: record.id,
    path: toAppDataUrl(record.path),
    message: "Image uploaded successfully",
  });
};

/**
 * Handles GET requests to retrieve all user-uploaded images.
 *
 * Returns a list of all images that were uploaded by users (not generated by AI).
 * This is useful for displaying a gallery of uploaded images or allowing users
 * to manage their image library.
 *
 * @returns A JSON response containing an array of image objects, each with:
 *   - `id`: Unique identifier
 *   - `path`: URL-accessible path to the image file
 *   - `is_uploaded`: Boolean (always true for uploaded images)
 *   - `created_at`: Timestamp when the image was uploaded
 *
 * @example
 * ```typescript
 * // Request: GET /api/v1/images/uploaded
 * const response = await handleImagesUploaded();
 * // Response: [{ id: "abc-123", path: "/app_data/images/...", ... }, ...]
 * ```
 */
export const handleImagesUploaded = async () => {
  // List all images marked as uploaded (i.e., user-uploaded)
  const imagesList = await listImages(true);
  
  // Convert file paths to URL-accessible paths
  const images = imagesList.map((image) => ({
    ...image,
    path: toAppDataUrl(image.path),
  }));
  return jsonResponse(images);
};

/**
 * Handles DELETE requests to remove an image from storage and database.
 *
 * Deletes both the image file from the filesystem and the database record.
 * If file deletion fails (e.g., file already deleted), the database record
 * is still removed to maintain consistency. This ensures the database doesn't
 * reference non-existent files.
 *
 * @param id - The unique identifier of the image to delete.
 * @returns A JSON response with:
 *   - `success`: Boolean indicating operation success
 *   - `message`: Success message
 *
 * @throws Returns error responses for:
 *   - 404: Image not found in database
 *
 * @example
 * ```typescript
 * // Request: DELETE /api/v1/images/abc-123
 * const response = await handleImagesDelete("abc-123");
 * // Response: { success: true, message: "Image deleted successfully" }
 * ```
 */
export const handleImagesDelete = async (id: string) => {
  // Check if image exists before attempting deletion
  const image = await getImageById(id);
  if (!image) {
    return jsonResponse({ detail: "Image not found" }, 404);
  }
  
  // Try to delete the file from filesystem
  // If this fails (file already deleted, permissions issue, etc.), log warning
  // but continue to delete database record
  try {
    await fs.unlink(image.path);
  } catch (error) {
    console.warn("Failed to delete image file:", error);
  }
  
  // Delete database record regardless of file deletion result
  // This prevents orphaned database records
  await deleteImageById(id);
  return jsonResponse({ success: true, message: "Image deleted successfully" });
};
