/**
 * Database operations for image assets.
 *
 * This module provides functions for managing image asset records in the database.
 * Image assets track images that are used in presentations, including both
 * uploaded images and generated images. The actual image files are stored
 * separately (in file system or cloud storage); this module only manages
 * the metadata and references.
 */

import { prisma } from "../db";

/**
 * Image asset record structure stored in the database.
 *
 * Represents metadata for an image used in presentations. The actual image
 * file is stored separately (referenced by the path), while this record
 * tracks the image's existence and origin.
 *
 * @property id - Unique identifier for the image asset.
 * @property path - File path or URL where the image file is stored. This
 *   can be a local file system path or a cloud storage URL.
 * @property is_uploaded - Boolean indicating whether this image was uploaded
 *   by a user (true) or generated by the system (false). Used for filtering
 *   and display purposes.
 * @property created_at - ISO 8601 timestamp string of when the image asset
 *   was created.
 */
export type ImageAssetRecord = {
  id: string;
  path: string;
  is_uploaded: boolean;
  created_at: string;
};

const rowToImage = (
  row: {
    id: string;
    path: string;
    is_uploaded: boolean;
    created_at: Date;
  } | null,
): ImageAssetRecord | null => {
  if (!row) return null;
  return {
    id: row.id,
    path: row.path,
    is_uploaded: row.is_uploaded,
    created_at: row.created_at.toISOString(),
  };
};

export const createImageAsset = async (
  payload: Omit<ImageAssetRecord, "created_at">,
): Promise<ImageAssetRecord> => {
  const now = new Date();

  const created = await prisma.imageAsset.create({
    data: {
      id: payload.id,
      path: payload.path,
      is_uploaded: payload.is_uploaded,
      created_at: now,
    },
  });

  return rowToImage(created)!;
};

export const listImages = async (
  isUploaded: boolean,
): Promise<ImageAssetRecord[]> => {
  const rows = await prisma.imageAsset.findMany({
    where: { is_uploaded: isUploaded },
    orderBy: { created_at: "desc" },
  });
  return rows.map(rowToImage).filter((r): r is ImageAssetRecord => r !== null);
};

export const getImageById = async (
  id: string,
): Promise<ImageAssetRecord | null> => {
  const row = await prisma.imageAsset.findUnique({
    where: { id },
  });
  return rowToImage(row);
};

export const deleteImageById = async (id: string): Promise<boolean> => {
  try {
    await prisma.imageAsset.delete({
      where: { id },
    });
    return true;
  } catch {
    return false;
  }
};
